# Generated by Django 5.2.1 on 2025-06-04 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='images',
            new_name='media_content',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='images',
            new_name='media_content',
        ),
    ]
