# Generated by Django 5.2.1 on 2025-06-04 09:33

import volunteer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0002_rename_images_event_media_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='media_content',
            field=models.FileField(blank=True, null=True, upload_to='event_content', validators=[volunteer.models.validate_media_file]),
        ),
        migrations.AlterField(
            model_name='news',
            name='media_content',
            field=models.FileField(blank=True, null=True, upload_to='news_content', validators=[volunteer.models.validate_media_file]),
        ),
    ]
