# Generated by Django 5.2.1 on 2025-05-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='company_email',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='company_owner',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='company_website',
        ),
        migrations.AddField(
            model_name='investor',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='investor',
            name='company_owner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investor',
            name='company_website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
